name: chatappui
services:
    chatappui:
        stdin_open: true
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules/
        ports:
            - 3000:3000
        image: chatappui:2